name: e_clinic_new
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 2.32.0
  firebase_auth: 4.20.0
  cloud_firestore: 4.17.4
  shared_preferences: 2.2.3
  provider: ^6.1.1
  image_picker: 1.1.2
  http: ^1.2.1
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
